const API_URL = 'https://yesems-sistema-1.onrender.com/api';
const token = localStorage.getItem('yesems_token');
let user = JSON.parse(localStorage.getItem('yesems_usuario') || 'null');
let profileLoaded = false;
if (!token || !user) window.location.replace('./cursos.html');
const message = document.querySelector('#settings-message');
function render(userData) { const name = `${userData.nombre || ''} ${userData.apellido || ''}`.trim(); document.querySelector('#profile-name').textContent = name; document.querySelector('#profile-email').textContent = userData.email || ''; document.querySelector('#profile-initial').textContent = (name[0] || 'A').toUpperCase(); document.querySelector('#nombre').value = userData.nombre || ''; document.querySelector('#apellido').value = userData.apellido || ''; document.querySelector('#telefono').value = userData.telefono || ''; document.querySelector('#fecha-nacimiento').value = String(userData.fecha_nacimiento || '').slice(0,10); document.querySelector('#curp').value = userData.curp || ''; document.querySelector('#email-readonly').textContent = userData.email || ''; document.querySelector('#folio-readonly').textContent = userData.folio || 'Se genera al confirmar una inscripción'; }
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { ...options.headers, Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.mensaje || 'No fue posible completar la acción.'); return data; }
async function load() { try { const data = await request(`${API_URL}/usuarios/mio`); profileLoaded = true; user = { ...user, ...data.usuario }; const { id_usuario, nombre, apellido, email, rol, folio } = user; localStorage.setItem('yesems_usuario', JSON.stringify({ id_usuario, nombre, apellido, email, rol, folio })); render(user); } catch (error) { message.textContent = error.message; render(user); document.querySelector('#settings-form button').disabled = true; } }
document.querySelector('#settings-form').addEventListener('submit', async (event) => { event.preventDefault(); if (!profileLoaded) { message.textContent = 'Recarga la ficha antes de guardar.'; return; } const form = event.currentTarget; if (!form.checkValidity()) return form.reportValidity(); const button = form.querySelector('button'); button.disabled = true; button.textContent = 'Guardando...'; message.className = ''; message.textContent = ''; try { const data = await request(`${API_URL}/usuarios/mio`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nombre: document.querySelector('#nombre').value.trim(), apellido: document.querySelector('#apellido').value.trim(), telefono: document.querySelector('#telefono').value.trim(), fecha_nacimiento: document.querySelector('#fecha-nacimiento').value, curp: document.querySelector('#curp').value.trim() }) }); profileLoaded = true; user = { ...user, ...data.usuario }; const { id_usuario, nombre, apellido, email, rol, folio } = user; localStorage.setItem('yesems_usuario', JSON.stringify({ id_usuario, nombre, apellido, email, rol, folio })); render(user); message.className = 'success'; message.textContent = 'Tus cambios se guardaron correctamente.'; } catch (error) { message.textContent = error.message; } finally { button.disabled = false; button.textContent = 'Guardar cambios'; } });
document.querySelector('#logout-button').addEventListener('click', () => { localStorage.removeItem('yesems_token'); localStorage.removeItem('yesems_usuario'); window.location.href = './cursos.html'; });
load();
const passwordLink = document.createElement('a');
passwordLink.href = './password.html?modo=cambiar';
passwordLink.textContent = 'Cambiar contraseña con un código por correo';
passwordLink.style.display = 'inline-block';
passwordLink.style.marginTop = '24px';
document.querySelector('#settings-form').after(passwordLink);
